config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :tickets, only: %i[index new create destroy]
  resources :tickets, only: [:show], format: { pdf: true }
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :burger_quantity, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["burger_quantity", "created_at", "drink_quantity", "id", "promo", "tokens", "updated_at", "veggie_quantity"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show destroy ]

  def index
    @tickets = Ticket.all.order(created_at: :desc)
    @burgers = Ticket.sum(:burger_quantity)
    @veggies = Ticket.sum(:veggie_quantity)
    @drinks = Ticket.sum(:drink_quantity)
    @token_total = Ticket.sum(:tokens)
  end

  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf { render pdf: 'ticket_pdf',
                   template: 'tickets/ticket_pdf',
                   page_size: 'A7',
                   margin: { bottom: 0 } }
    end
  end

  def new
    @veggies = Ticket.sum(:veggie_quantity)
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    set_default_values(@ticket)
    @ticket.tokens = (@ticket.burger_quantity + @ticket.veggie_quantity) * 1.5 + @ticket.drink_quantity * 0.5
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
    end
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:burger_quantity, :veggie_quantity, :drink_quantity, :promo)
  end

  def set_default_values(ticket)
    ticket.burger_quantity ||= 0
    ticket.veggie_quantity ||= 0
    ticket.drink_quantity ||= 0
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LCB</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to tickets_path, class: "navbar-brand" do %>
      <%= image_tag "horizontal.jpg", class: "navbar-brand font-weight-bold no-underline", style: "height: 50px; width: 180px;" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Añadir ticket", new_ticket_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Totales", tickets_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "logo.jpg", style: "height: 45px;", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Cerrar sesión", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tickets/index.html.erb
<%= link_to "Crear nuevo ticket ->", new_ticket_path, class: "btn btn-primary mb-4", autofocus: true %>

<h1 class="fw-bold">Cómo vamos hasta ahora</h1>
<div class="row align-items-md-stretch mb-3">
  <div class="col-sm-12 col-md-4">
    <div style="border-radius: 8px;" class="p-4 bg-light border shadow-sm">
      <h1 class="fw-bold text-primary"><%= @burgers %></h1>
      <p>Hamburguesas de carne vendidas.</p>
    </div>
  </div>
  <div class="col-sm-12 col-md-4 mb-3">
    <div style="border-radius: 8px;" class="p-4 bg-light border shadow-sm">
      <h1 class="fw-bold text-primary"><%= @veggies %></h1>
      <p>Hamburguesas veggie vendidas.</p>
    </div>
  </div>
  <div class="col-sm-12 col-md-4 mb-3">
    <div style="border-radius: 8px;" class="p-4 bg-light border shadow-sm">
      <h1 class="fw-bold text-primary"><%= @drinks %></h1>
      <p>Bebidas vendidas.</p>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 mb-3">
    <div style="border-radius: 8px;" class="p-4 bg-light border shadow-sm">
      <h1 class="fw-bold text-primary"><%= @token_total %></h1>
      <p>Tokens vendidos.</p>
    </div>
  </div>
  <div class="col-sm-12 col-md-6 mb-3">
    <div style="border-radius: 8px;" class="p-4 bg-light border shadow-sm">
      <h1 class="fw-bold text-primary"><%= number_to_currency(@token_total * 4000, delimiter: '.', precision: 0 ) %></h1>
      <p>Total vendido.</p>
    </div>
  </div>
</div>

<h1><strong>Todos los tickets</strong></h1>
<table class="table table-striped border">
  <thead>
    <tr>
      <th scope="col">Tickets</th>
      <th scope="col">Hamburguesas de carnes</th>
      <th scope="col">Hamburguesas veggie</th>
      <th scope="col">Bebidas</th>
      <th scope="col">Tokens</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% @tickets.each do |ticket| %>
    <tr>
      <td><%= link_to "Ticket ##{ticket.id}", ticket_path(ticket) %></td>
      <td><%= ticket.burger_quantity %></td>
      <td><%= ticket.veggie_quantity %></td>
      <td><%= ticket.drink_quantity %></td>
      <td><%= ticket.tokens %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<script>
  document.addEventListener('keydown', function(event) {
    if (event.key === 'N' || event.key === 'n') {
      window.location.href = '<%= new_ticket_path %>';
    }
  });
</script>

app/views/tickets/new.html.erb
<div class="container">
  <div class="mb-3">
    <%= link_to "<- Ver totales", tickets_path, class: "btn btn-primary" %>
  </div>
  <div class="row justify-content-center mb-5">
    <div class="col-sm-12 col-md-6">
      <div style="border-radius: 12px;" class="p-4 bg-light border shadow-sm">
        <h1><strong>Crear nuevo ticket</strong></h1>
        <%= simple_form_for(@ticket) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :burger_quantity, label: "¿Cuántas hamburguesas de carne son?", autofocus: true %>
            <% if @veggies <= 125 %>
            <%= f.input :veggie_quantity, label: "¿Cuántas hamburguesas veggie son? Quedan #{126 - @veggies} disponibles" %>
            <% end %>
            <%= f.input :drink_quantity, label: "¿Cuántas bebidas son?" %>
            <%= f.input :promo, as: :hidden, input_html: { value: false } %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Crear ticket ->", class: "btn btn-light" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('keydown', function(event) {
    if (event.key === 'T' || event.key === 't') {
      window.location.href = '<%= tickets_path %>';
    }
  });
</script>

app/views/tickets/show.html.erb
<h1>Ticket #<%= @ticket.id %></h1>
<% if @ticket.burger_quantity.positive? %>
  <h3><%= @ticket.burger_quantity %> hamburguesas de carne</h3>
<% end %>
<% if @ticket.veggie_quantity.positive? %>
  <h3><%= @ticket.veggie_quantity %> hamburguesas veggie</h3>
<% end %>
<% if @ticket.drink_quantity.positive? %>
  <h3><%= @ticket.drink_quantity %> bebidas</h3>
<% end %>
<h3><%= @ticket.tokens  %> tokens</h3>
<%= link_to "Imprimir ->", "#{ticket_path(@ticket)}.pdf", autofocus: true, target: 'blank', class: "btn btn-primary"%> <br><hr>
<code>Presiona N para crear un nuevo ticket.</code> <br>
<p class="mt-2"><code>Presiona T para ver los totales.</code></p>
<%= button_to "Eliminar este ticket", @ticket, method: :delete, class: "btn btn-danger text-white" %>

<script>
  document.addEventListener('keydown', function(event) {
    if (event.key === 'N' || event.key === 'n') {
      window.location.href = '<%= new_ticket_path %>';
    }
  });

  document.addEventListener('keydown', function(event) {
    if (event.key === 'T' || event.key === 't') {
      window.location.href = '<%= tickets_path %>';
    }
  });
</script>

app/views/tickets/ticket_pdf.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Ticket #<%= @ticket_id %></title>
    <style>
      body {
        font-family: sans-serif;
      }
    </style>
  </head>
  <body style="text-align: center;">
    <%= image_tag wicked_pdf_asset_base64('ticket.jpg'), style: "height: 125px;" %>
    <h2><strong>Ticket Caja 1 #<%= @ticket.id %></strong></h2>
    <% if @ticket.burger_quantity.positive? %>
      <p><%= @ticket.burger_quantity %> hamburguesas de carne</p>
    <% end %>
    <% if @ticket.veggie_quantity.positive? %>
      <p><%= @ticket.veggie_quantity %> hamburguesas veggie</p>
    <% end %>
    <% if @ticket.drink_quantity.positive? %>
      <p><%= @ticket.drink_quantity %> bebidas</p>
    <% end %>
    <hr>
    <p><strong><%= @ticket.tokens %> tokens</strong></p>
    <hr>
    <p>Ticket creado a las <%= @ticket.created_at.in_time_zone("America/Santiago").strftime("%H:%M") %></p>
  </body>
</html>